# Environment variables
# - HOST_NAME
# - USER_NAME
 
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-browsers
 
    steps:
      - checkout
 
      - add_ssh_keys:
          fingerprints:
            - "55:14:1c:69:99:aa:02:8e:a6:97:5c:c9:a3:fb:25:4c"
 
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan -p 10022 ${HOST_NAME} >> ~/.ssh/known_hosts
 
      - deploy:
          name: Start master deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                	rsync -av --delete --rsh="ssh -p 10022" --exclude='.git' --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}:/var/www/html/
            fi